### ISSUE TITLE
Update RFTools Quarry Shapecard Recipe

### ISSUE THREAD

**Issue by slidingmike** [BreakfastCraft/Spilled-Juice-Modpack#125]

**Comment by slidingmike** [comment]
Gate it?

**Comment by mote** [comment]
Options we discussed in chat:
* gate w/ nether resources (netherwart blocks, glowstone)
* require w/ more expensive resources (diamond blocks)
* require more RF

I'm fine w/ any of these.

If you do gate this rather than making it more expensive, you'll want to gate BC quarry the same way

**Comment by NiSiSuinegEht** [comment]
I think the builder would be better to gate, rather than the card.  There are a few different ways to accomplish mass ore harvesting that don't involve the actual quarry card.  Making the builder more expensive, more power hungry, or both would be a good gate.  Will there be a similar gating applied to other mass block breaking capabilities as well?

**Comment by demethan** [comment]
No gate required.  there are no easy power generation in that pack.  it is not useful until the end game anyways, even if you get all the cards and builder.  Same goes for the BC builder since you need the BC power generation. To get the high  efficiency fuels for it is end game too.

**Comment by UnNinja** [comment]
I'm with dem. It really doesn't need any changes. Plus then it raises the question NiSi did: do we apply the same type of changes to all the other options? Or are we just picking on rftools because it _feels_ strong.
If we absolutely must make a change to just the rftools quarry because "lol op", lowering I:quarryBaseSpeed=8 to something more in line with buildcraft (which afaik is the only other in-world quarry) is probably the least worst choice.

**Comment by demethan** [comment]
` lowering I:quarryBaseSpeed=8`

is an ok compromise.

**Comment by slidingmike** [comment]
Completed

**Comment by UnNinja** [comment]
we had decided to leave this as default in discord. guess I didn't remembered to update this

**Comment by slidingmike** [comment]
Fixed in new release
